### ISSUE TITLE
Code needs updating to latest Dart and Flutter

### ISSUE THREAD

**Issue by cliffordh** [lohanidamodar/flutter_firebase_starter#5]
Receiving a bunch of deprecation warnings and errors when cloning this project, for example:

avatar.dart:25 'overflow' is deprecated and shouldn't be used. Use clipBehavior instead. See the migration guide in flutter.dev/go/clip-behavior. This feature was deprecated after v1.22.0-12.0.pre..

auth_dialog.dart:33 The named parameter 'child' isn't defined.

➜  flutter_firebase_starter git:(master) flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-10.0.pre.359, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
[✓] VS Code (version 1.49.1)
[✓] Connected device (2 available)

• No issues found!
➜  flutter_firebase_star

**Comment by cliffordh** [comment]
Ignore the 'named parameter child' report, must have been an IDE glitch. But the deprecation issue still exists.

**Comment by cliffordh** [comment]
widget_test.dart: 11 Unused import: 'package:firebasestarter/main.dart'.
widget_test.dart:16 The function 'MyApp' isn't defined.

**Comment by cliffordh** [comment]
pubspec.yaml is out of date when building for iOS, lots of CocoaPods errors

**Comment by lohanidamodar** [comment]
@cliffordh Thank you for the issues
1. I think for iOS, you can clean the pod by deleting podfile, then `flutter clean` then `flutter run` to generate new podfiles with updated informations, will make sure to update that as well
2. For deprecation, please confirm the updates are available in stable version as well. If not it will have to wait.

I will make sure to check the issues as well.

**Comment by cliffordh** [comment]
@lohanidamodar thanks for the reply. Nice to see you have plans to maintain this a bit. I should also note that the Crashlytics run script is now out of date since Fabric was retired.

**Comment by lohanidamodar** [comment]
@cliffordh Thanks for the update. Yes I plan to support this, as I myself am using this.

**Comment by lohanidamodar** [comment]
@cliffordh 
1. You can ignore the test file errors for now, I have not been able to implement testing yet however I am planning to implement them soon, not sure how soon though
2. I am unable to reproduce the deprecation issue even in flutter master channel, however based on the link you shared, I have upgraded that too to use `clipBehavior` instead of overflow. 

Updates will be published in all the relevant branches soon

**Comment by lohanidamodar** [comment]
@cliffordh I have made the updates and pushed in https://github.com/lohanidamodar/flutter_firebase_starter/tree/feature/dependency-updates branch.

It would be great if you could help me test if everything is in order. Thanks again.

**Comment by cliffordh** [comment]
Great thanks. I will check it out @lohanidamodar

**Comment by lohanidamodar** [comment]
@cliffordh Hi, did you have time to test? 
Thank you

**Comment by lohanidamodar** [comment]
PR #8 should fix this. If you have further problems feel free to reopen the issue.
